# Generated by Django 5.1.6 on 2025-03-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='schema_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
