# Generated by Django 5.1.6 on 2025-03-06 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_tenant_schema_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tenant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='expenses.tenant'),
            preserve_default=False,
        ),
    ]
