# Generated by Django 5.1.6 on 2025-03-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expenses_tenant_alter_company_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
